### ISSUE TITLE
SISGEO D-TILTMETER can not read value

### ISSUE THREAD

**Issue by fukemy** [sanny32/OpenModScan#24]
Hi, I tried to read the value from SISGEO D-TILTMETER, I can not find any forum to ask this question, I am so sorry by bothering you. But can you give me some advice?
 here  is the SISGEO device:
 
 
![1734951562242](https://github.com/user-attachments/assets/11833e34-937b-4a3c-bac1-b8cc0732a17b)

Here is the way I plug the SISGEO device to CR1000x:

![1734951562267](https://github.com/user-attachments/assets/fc03d0e5-36fc-41be-ac60-863fea03877f)

In OpenModScan, I can only using COM1 to connect, but I tried everything but can not get result from SISGEO device:

![Untitled](https://github.com/user-attachments/assets/2181f42e-b1f5-438b-88c3-0d6d298f7b18)

**Comment by sanny32** [comment]
Hello @fukemy. You can try to scan connection parameters via menu Connection->MODBUS Scanner 
![изображение](https://github.com/user-attachments/assets/1260466f-73d3-4806-b50f-e9e05f709175)

And then scan device with different daud rate, data bits, device id and other parameters.

![изображение](https://github.com/user-attachments/assets/9db71a0d-0d72-4481-a449-54a3025703cd)

**Comment by ortegahernandes** [comment]
sorry to join the conversation. 

I don't know your equipment, but it was clear that your communication has to be done via com4 as it has the same name(CR1000x) you mentioned that it communicates with and not com1, com1 is very possibly an internal port on your computer. 

Now, if open modscan doesn't see the com4, perhaps it's a problem in the software that went unnoticed, because it appears in your device manager.
